"""Mudando o campo senha_hash para senha na tabela Usuario

Revision ID: d3624ef5c37b
Revises: f269fbb26c7f
Create Date: 2020-06-08 10:25:44.403638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3624ef5c37b'
down_revision = 'f269fbb26c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha', sa.String(length=128), nullable=True))
    op.drop_column('usuario', 'senha_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'senha')
    # ### end Alembic commands ###
