"""Modificando tabela usuário para receber vários telefones. Criando tabela Telefones e linkando com a tabela de usuários

Revision ID: f37a2be08737
Revises: f93236a6de3e
Create Date: 2020-06-06 13:03:11.405047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37a2be08737'
down_revision = 'f93236a6de3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.add_column('usuario', sa.Column('nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nascimento')
    op.drop_column('usuario', 'cpf')
    op.drop_table('telefone')
    # ### end Alembic commands ###
